musteriadi= input("Adınızı giriniz: ")
musterisoyadi= input("Soyadınızı giriniz: ")
musteriadivesoyadi=musteriadi+' '+musterisoyadi
musteridogumyili= input("Doğum yılınızı giriniz: ")
musteriyasi=2021-int(musteridogumyili)
musteritckimlik= input("TC Kimlik numaranızı giriniz: ")
musteriadres= input("Adresinizi giriniz: ")
mustericinsiyet= input("Cinsiyetinizi yazınız: ")
print ("Müşteri bilgileri")
print("Müşteri adı ve soyadı: "+musteriadivesoyadi)
print("Müşteri yaşı: "+str(musteriyasi))
print("Müşteri TC Kimlik numarası: "+musteritckimlik)
print("Müşteri Adresi: "+musteriadres)
print("Müşteri cinsiyeti: "+mustericinsiyet)